### ISSUE TITLE
横屏时如何修改hotseat位置？

### ISSUE THREAD

**Issue by zhenghx1105** [fookwood/Launcher3#13]
Launcher3 横屏时默认hotseat位置在左边，怎么调整到左边或是底部？谢谢。

**Comment by fookwood** [comment]
平板上么？

**Comment by zhenghx1105** [comment]
手机,AndroidMainfest.xml 调成可以自动旋转屏幕

**Comment by fookwood** [comment]
建议研究下DynamicGrid的layout方法

**Comment by zhenghx1105** [comment]
thx！ 这个我研究过了 修改里面hotseat的gravity=Gravity.LEFT。
但是会出现一个问题，修改横屏hotseat在左边的时候 长按hostseat图标的时候  放开及时我不拖动默认会把hotseat的快捷图标放在worksapce上 好奇怪的问题。可能还有一些地方需要修改

**Comment by fookwood** [comment]
你可以跟踪下workspace的onDrop方法，看看为啥放到了workspace上

**Comment by zhenghx1105** [comment]
主要可能没有修改完全，造成长按时候造成hotseat默认图标位置为不可放置，找到临近的workspace的位置为放置，手指移开就放到worksapce里了。
