### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by yuchuangu85** [fookwood/Launcher3#15]
我在导入最新的Launcher3时，提示没有BackupProtos.java这个文件，查找让我用这个命令：
protoc --javanano_out=src/ -I protos protos/backup.proto
去生成，但是找了很多资料没有找到怎么执行这个命令，看到你这个项目中有这个文件，但是导入最新的项目不行，想请教一下，这个文件是是怎么生成的，可以提供个详细的生成步骤吗？

多谢了！

**Comment by fookwood** [comment]
这个项目中我好像没找到这个文件
Protobuf 是google的数据交换格式，主要资料在这里：
https://developers.google.com/protocol-buffers/docs/reference/java-generated

**Comment by yuchuangu85** [comment]
好的，我看看，研究两天没搞出来，看google的github网站上的项目有人问也是很多搞不出来。
