### ISSUE TITLE
给launcher设置左屏

### ISSUE THREAD

**Issue by tq01m4m** [fookwood/Launcher3#21]
给launcher设置左屏后，滑动的时候屏幕会变暗，滑动完毕屏幕又恢复原来的亮度，请问是什么原因。谢谢。

**Comment by fookwood** [comment]
Workspace.updatePageAlphaValues(int) 方法会在Workspace.screenScrolled(int)方法中被调用
而Workspace.screenScrolled(int)会在屏幕滑动的时候被调用
