### ISSUE TITLE
运行报错，求指教

### ISSUE THREAD

**Issue by Congeek** [fookwood/Launcher3#22]
Error while executing: am start -n "com.android.launcher3/com.android.launcher3.ToggleWeightWatcher" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.android.launcher3/.ToggleWeightWatcher }
Error type 3
Error: Activity class {com.android.launcher3/com.android.launcher3.ToggleWeightWatcher} does not exist.

小米3运行不了，不是很懂

**Comment by fookwood** [comment]
com.android.launcher3/com.android.launcher3.ToggleWeightWatcher 你可以把这个Activity删掉，
然后再给 com.android.launcher3.Launcher 加个 <category android:name="android.intent.category.LAUNCHER" /> 属性

**Comment by Congeek** [comment]
可以了，谢谢
