### ISSUE TITLE
Add new left screen

### ISSUE THREAD

**Issue by oguncan** [fookwood/Launcher3#27]
I want to add a simple blank page to the left side of the launcher. Can u help me guys? Please.

Like that..
<img width="192" alt="X8PB4" src="https://user-images.githubusercontent.com/23150924/82125133-951b8800-97ac-11ea-9c58-69f3d707a190.png">

Thanks..

**Comment by fookwood** [comment]
return `true` in Launcher.hasCustomContentToLeft()
then add view in Workspace.addToCustomContentPage()

source: [https://fookwood.com/launcher-left-screen](https://fookwood.com/launcher-left-screen)

**Comment by oguncan** [comment]
Thank u very much! its working.
